export const HealthData = [
  {
    icon: require('@/src/assets/images/water_logo.png'),
    title: 'Water',
    value: '2100 ml',
    subtitle: 'Goal: 2L',
    backgroundColor: '#E0F2FE',
    image: require('@/src/assets/images/wave.png'),
  },
  {
    icon: require('@/src/assets/images/weight_logo.png'),
    title: 'Weight',
    value: '75kg',
    subtitle: 'Goal: 65kg',
    backgroundColor: '#FEF8E8',
    image: require('@/src/assets/images/measure.png'),
  },
  // {
  //   icon: require('@/src/assets/images/water_logo.png'),
  //   title: 'Height',
  //   value: '178 cm',
  //   subtitle: 'Goal: 180 cm',
  //   backgroundColor: '#F4F4FF',
  //   image: require('@/src/assets/images/wave.png'),
  // },
  // {
  //   icon: require('@/src/assets/images/weight_logo.png'),
  //   title: 'Sleep',
  //   value: '6.5 hrs',
  //   subtitle: 'Goal: 8 hrs',
  //   backgroundColor: '#F0F9FF',
  //   image: require('@/src/assets/images/wave.png'),
  // },
  // {
  //   icon: require('@/src/assets/images/weight_logo.png'),
  //   title: 'Steps',
  //   value: '8000',
  //   subtitle: 'Goal: 10,000',
  //   backgroundColor: '#E6FFF4',
  //   image: require('@/src/assets/images/wave.png'),
  // },
  // {
  //   icon: require('@/src/assets/images/water_logo.png'),
  //   title: 'Calories',
  //   value: '1600 kcal',
  //   subtitle: 'Goal: 2000 kcal',
  //   backgroundColor: '#FFEFEF',
  //   image: require('@/src/assets/images/wave.png'),
  // },
];
